name: docker-test
on:
  workflow_dispatch:

jobs:

  docker-browsers:
    runs-on: ubuntu-22.04
    container:
      image: cypress/browsers:node-20.10.0-chrome-121.0.6167.85-1-ff-118.0.2-edge-118.0.2088.46-1
      options: --user 1001
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Cypress tests
        uses: cypress-io/github-action@v6
        with:
          working-directory: e2e
          config-file: custom.config.ts
          browser: chrome
